type Ingredient = {
  name: string;
  unit: string;
  average_price: number;
};

type Recipe = {
  name: string;
  ingredients: { name: string; quantity: number }[];
};

type AveragePricesType = {
  states: Record<string, { ingredients: Ingredient[] }>;
  recipes: Recipe[];
};

export const pizzariaData: AveragePricesType = {
  states: {
    SP: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.0 },
        { name: "Molho de Tomate", unit: "kg", average_price: 4.5 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 30.0 },
        { name: "Calabresa", unit: "kg", average_price: 20.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 25.0 },
        { name: "Milho", unit: "kg", average_price: 8.0 },
        { name: "Azeitonas", unit: "kg", average_price: 18.0 },
        { name: "Ovos", unit: "dz", average_price: 10.0 },
        { name: "Presunto", unit: "kg", average_price: 30.0 },
        { name: "Cebola", unit: "kg", average_price: 5.0 },
        { name: "Manjericão", unit: "kg", average_price: 7.0 },
      ],
    },
    RJ: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.5 },
        { name: "Molho de Tomate", unit: "kg", average_price: 4.8 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 32.0 },
        { name: "Calabresa", unit: "kg", average_price: 22.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 27.0 },
        { name: "Milho", unit: "kg", average_price: 9.0 },
        { name: "Azeitonas", unit: "kg", average_price: 20.0 },
        { name: "Ovos", unit: "dz", average_price: 11.0 },
        { name: "Presunto", unit: "kg", average_price: 31.0 },
        { name: "Cebola", unit: "kg", average_price: 6.0 },
        { name: "Manjericão", unit: "kg", average_price: 8.0 },
      ],
    },
    MG: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.2 },
        { name: "Molho de Tomate", unit: "kg", average_price: 4.7 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 31.0 },
        { name: "Calabresa", unit: "kg", average_price: 21.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 26.0 },
        { name: "Milho", unit: "kg", average_price: 8.5 },
        { name: "Azeitonas", unit: "kg", average_price: 19.0 },
        { name: "Ovos", unit: "dz", average_price: 9.0 },
        { name: "Presunto", unit: "kg", average_price: 32.0 },
        { name: "Cebola", unit: "kg", average_price: 4.0 },
        { name: "Manjericão", unit: "kg", average_price: 6.0 },
      ],
    },
    ES: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.3 },
        { name: "Molho de Tomate", unit: "kg", average_price: 4.6 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 31.5 },
        { name: "Calabresa", unit: "kg", average_price: 21.5 },
        { name: "Frango Desfiado", unit: "kg", average_price: 26.5 },
        { name: "Milho", unit: "kg", average_price: 8.2 },
        { name: "Azeitonas", unit: "kg", average_price: 19.5 },
        { name: "Ovos", unit: "dz", average_price: 8.0 },
        { name: "Presunto", unit: "kg", average_price: 33.0 },
        { name: "Cebola", unit: "kg", average_price: 3.0 },
        { name: "Manjericão", unit: "kg", average_price: 5.0 },
      ],
    },
    PR: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.4 },
        { name: "Molho de Tomate", unit: "kg", average_price: 4.9 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 32.5 },
        { name: "Calabresa", unit: "kg", average_price: 22.5 },
        { name: "Frango Desfiado", unit: "kg", average_price: 27.5 },
        { name: "Milho", unit: "kg", average_price: 8.3 },
        { name: "Azeitonas", unit: "kg", average_price: 20.5 },
        { name: "Ovos", unit: "dz", average_price: 7.0 },
        { name: "Presunto", unit: "kg", average_price: 34.0 },
        { name: "Cebola", unit: "kg", average_price: 2.0 },
        { name: "Manjericão", unit: "kg", average_price: 4.0 },
      ],
    },
    SC: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.6 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.0 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 33.0 },
        { name: "Calabresa", unit: "kg", average_price: 23.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 28.0 },
        { name: "Milho", unit: "kg", average_price: 8.7 },
        { name: "Azeitonas", unit: "kg", average_price: 21.0 },
        { name: "Ovos", unit: "dz", average_price: 6.0 },
        { name: "Presunto", unit: "kg", average_price: 35.0 },
        { name: "Cebola", unit: "kg", average_price: 1.0 },
        { name: "Manjericão", unit: "kg", average_price: 3.0 },
      ],
    },
    RS: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.7 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.1 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 34.0 },
        { name: "Calabresa", unit: "kg", average_price: 24.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 29.0 },
        { name: "Milho", unit: "kg", average_price: 8.9 },
        { name: "Azeitonas", unit: "kg", average_price: 21.5 },
        { name: "Ovos", unit: "dz", average_price: 5.0 },
        { name: "Presunto", unit: "kg", average_price: 36.0 },
        { name: "Cebola", unit: "kg", average_price: 0.5 },
        { name: "Manjericão", unit: "kg", average_price: 2.0 },
      ],
    },
    MS: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.8 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.2 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 35.0 },
        { name: "Calabresa", unit: "kg", average_price: 25.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 30.0 },
        { name: "Milho", unit: "kg", average_price: 9.0 },
        { name: "Azeitonas", unit: "kg", average_price: 22.0 },
        { name: "Ovos", unit: "dz", average_price: 4.0 },
        { name: "Presunto", unit: "kg", average_price: 37.0 },
        { name: "Cebola", unit: "kg", average_price: 0.4 },
        { name: "Manjericão", unit: "kg", average_price: 1.0 },
      ],
    },
    MT: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 5.9 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.3 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 36.0 },
        { name: "Calabresa", unit: "kg", average_price: 26.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 31.0 },
        { name: "Milho", unit: "kg", average_price: 9.2 },
        { name: "Azeitonas", unit: "kg", average_price: 22.5 },
        { name: "Ovos", unit: "dz", average_price: 3.0 },
        { name: "Presunto", unit: "kg", average_price: 38.0 },
        { name: "Cebola", unit: "kg", average_price: 0.3 },
        { name: "Manjericão", unit: "kg", average_price: 0.5 },
      ],
    },
    GO: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.0 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.4 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 37.0 },
        { name: "Calabresa", unit: "kg", average_price: 27.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 32.0 },
        { name: "Milho", unit: "kg", average_price: 9.5 },
        { name: "Azeitonas", unit: "kg", average_price: 23.0 },
        { name: "Ovos", unit: "dz", average_price: 2.0 },
        { name: "Presunto", unit: "kg", average_price: 39.0 },
        { name: "Cebola", unit: "kg", average_price: 0.2 },
        { name: "Manjericão", unit: "kg", average_price: 0.4 },
      ],
    },
    DF: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.1 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.5 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 38.0 },
        { name: "Calabresa", unit: "kg", average_price: 28.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 33.0 },
        { name: "Milho", unit: "kg", average_price: 9.7 },
        { name: "Azeitonas", unit: "kg", average_price: 23.5 },
        { name: "Ovos", unit: "dz", average_price: 1.0 },
        { name: "Presunto", unit: "kg", average_price: 40.0 },
        { name: "Cebola", unit: "kg", average_price: 0.1 },
        { name: "Manjericão", unit: "kg", average_price: 0.3 },
      ],
    },
    BA: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.2 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.6 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 39.0 },
        { name: "Calabresa", unit: "kg", average_price: 29.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 34.0 },
        { name: "Milho", unit: "kg", average_price: 10.0 },
        { name: "Azeitonas", unit: "kg", average_price: 24.0 },
        { name: "Ovos", unit: "dz", average_price: 10.0 },
        { name: "Presunto", unit: "kg", average_price: 41.0 },
        { name: "Cebola", unit: "kg", average_price: 0.1 },
        { name: "Manjericão", unit: "kg", average_price: 0.0 },
      ],
    },
    SE: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.3 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.7 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 40.0 },
        { name: "Calabresa", unit: "kg", average_price: 30.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 35.0 },
        { name: "Milho", unit: "kg", average_price: 10.2 },
        { name: "Azeitonas", unit: "kg", average_price: 24.5 },
        { name: "Ovos", unit: "dz", average_price: 9.0 },
        { name: "Presunto", unit: "kg", average_price: 42.0 },
        { name: "Cebola", unit: "kg", average_price: 0.2 },
        { name: "Manjericão", unit: "kg", average_price: 0.1 },
      ],
    },
    AL: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.4 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.8 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 41.0 },
        { name: "Calabresa", unit: "kg", average_price: 31.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 36.0 },
        { name: "Milho", unit: "kg", average_price: 10.5 },
        { name: "Azeitonas", unit: "kg", average_price: 25.0 },
        { name: "Ovos", unit: "dz", average_price: 8.0 },
        { name: "Presunto", unit: "kg", average_price: 43.0 },
        { name: "Cebola", unit: "kg", average_price: 0.3 },
        { name: "Manjericão", unit: "kg", average_price: 0.2 },
      ],
    },
    PE: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.5 },
        { name: "Molho de Tomate", unit: "kg", average_price: 5.9 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 42.0 },
        { name: "Calabresa", unit: "kg", average_price: 32.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 37.0 },
        { name: "Milho", unit: "kg", average_price: 10.7 },
        { name: "Azeitonas", unit: "kg", average_price: 25.5 },
        { name: "Ovos", unit: "dz", average_price: 7.0 },
        { name: "Presunto", unit: "kg", average_price: 44.0 },
        { name: "Cebola", unit: "kg", average_price: 0.4 },
        { name: "Manjericão", unit: "kg", average_price: 0.3 },
      ],
    },
    PB: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.6 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.0 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 43.0 },
        { name: "Calabresa", unit: "kg", average_price: 33.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 38.0 },
        { name: "Milho", unit: "kg", average_price: 11.0 },
        { name: "Azeitonas", unit: "kg", average_price: 26.0 },
        { name: "Ovos", unit: "dz", average_price: 6.0 },
        { name: "Presunto", unit: "kg", average_price: 45.0 },
        { name: "Cebola", unit: "kg", average_price: 0.5 },
        { name: "Manjericão", unit: "kg", average_price: 0.4 },
      ],
    },
    RN: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.7 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.1 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 44.0 },
        { name: "Calabresa", unit: "kg", average_price: 34.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 39.0 },
        { name: "Milho", unit: "kg", average_price: 11.2 },
        { name: "Azeitonas", unit: "kg", average_price: 26.5 },
        { name: "Ovos", unit: "dz", average_price: 5.0 },
        { name: "Presunto", unit: "kg", average_price: 46.0 },
        { name: "Cebola", unit: "kg", average_price: 0.6 },
        { name: "Manjericão", unit: "kg", average_price: 0.5 },
      ],
    },
    CE: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.8 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.2 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 45.0 },
        { name: "Calabresa", unit: "kg", average_price: 35.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 40.0 },
        { name: "Milho", unit: "kg", average_price: 11.5 },
        { name: "Azeitonas", unit: "kg", average_price: 27.0 },
        { name: "Ovos", unit: "dz", average_price: 4.0 },
        { name: "Presunto", unit: "kg", average_price: 47.0 },
        { name: "Cebola", unit: "kg", average_price: 0.7 },
        { name: "Manjericão", unit: "kg", average_price: 0.6 },
      ],
    },
    PI: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 6.9 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.3 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 46.0 },
        { name: "Calabresa", unit: "kg", average_price: 36.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 41.0 },
        { name: "Milho", unit: "kg", average_price: 11.7 },
        { name: "Azeitonas", unit: "kg", average_price: 27.5 },
        { name: "Ovos", unit: "dz", average_price: 3.0 },
        { name: "Presunto", unit: "kg", average_price: 48.0 },
        { name: "Cebola", unit: "kg", average_price: 0.8 },
        { name: "Manjericão", unit: "kg", average_price: 0.7 },
      ],
    },
    MA: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.0 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.4 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 47.0 },
        { name: "Calabresa", unit: "kg", average_price: 37.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 42.0 },
        { name: "Milho", unit: "kg", average_price: 12.0 },
        { name: "Azeitonas", unit: "kg", average_price: 28.0 },
        { name: "Ovos", unit: "dz", average_price: 2.0 },
        { name: "Presunto", unit: "kg", average_price: 49.0 },
        { name: "Cebola", unit: "kg", average_price: 0.9 },
        { name: "Manjericão", unit: "kg", average_price: 0.8 },
      ],
    },
    PA: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.1 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.5 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 48.0 },
        { name: "Calabresa", unit: "kg", average_price: 38.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 43.0 },
        { name: "Milho", unit: "kg", average_price: 12.2 },
        { name: "Azeitonas", unit: "kg", average_price: 28.5 },
        { name: "Ovos", unit: "dz", average_price: 1.0 },
        { name: "Presunto", unit: "kg", average_price: 50.0 },
        { name: "Cebola", unit: "kg", average_price: 1.0 },
        { name: "Manjericão", unit: "kg", average_price: 1.0 },
      ],
    },
    AP: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.2 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.6 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 49.0 },
        { name: "Calabresa", unit: "kg", average_price: 39.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 44.0 },
        { name: "Milho", unit: "kg", average_price: 12.5 },
        { name: "Azeitonas", unit: "kg", average_price: 29.0 },
        { name: "Ovos", unit: "dz", average_price: 0.0 },
        { name: "Presunto", unit: "kg", average_price: 51.0 },
        { name: "Cebola", unit: "kg", average_price: 1.1 },
        { name: "Manjericão", unit: "kg", average_price: 1.1 },
      ],
    },
    TO: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.3 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.7 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 50.0 },
        { name: "Calabresa", unit: "kg", average_price: 40.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 45.0 },
        { name: "Milho", unit: "kg", average_price: 12.7 },
        { name: "Azeitonas", unit: "kg", average_price: 29.5 },
        { name: "Ovos", unit: "dz", average_price: 1.0 },
        { name: "Presunto", unit: "kg", average_price: 52.0 },
        { name: "Cebola", unit: "kg", average_price: 1.2 },
        { name: "Manjericão", unit: "kg", average_price: 1.2 },
      ],
    },
    RO: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.4 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.8 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 51.0 },
        { name: "Calabresa", unit: "kg", average_price: 41.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 46.0 },
        { name: "Milho", unit: "kg", average_price: 13.0 },
        { name: "Azeitonas", unit: "kg", average_price: 30.0 },
        { name: "Ovos", unit: "dz", average_price: 2.0 },
        { name: "Presunto", unit: "kg", average_price: 53.0 },
        { name: "Cebola", unit: "kg", average_price: 1.3 },
        { name: "Manjericão", unit: "kg", average_price: 1.3 },
      ],
    },
    AC: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.5 },
        { name: "Molho de Tomate", unit: "kg", average_price: 6.9 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 52.0 },
        { name: "Calabresa", unit: "kg", average_price: 42.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 47.0 },
        { name: "Milho", unit: "kg", average_price: 13.2 },
        { name: "Azeitonas", unit: "kg", average_price: 30.5 },
        { name: "Ovos", unit: "dz", average_price: 3.0 },
        { name: "Presunto", unit: "kg", average_price: 54.0 },
        { name: "Cebola", unit: "kg", average_price: 1.4 },
        { name: "Manjericão", unit: "kg", average_price: 1.4 },
      ],
    },
    AM: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.6 },
        { name: "Molho de Tomate", unit: "kg", average_price: 7.0 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 53.0 },
        { name: "Calabresa", unit: "kg", average_price: 43.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 48.0 },
        { name: "Milho", unit: "kg", average_price: 13.5 },
        { name: "Azeitonas", unit: "kg", average_price: 31.0 },
        { name: "Ovos", unit: "dz", average_price: 4.0 },
        { name: "Presunto", unit: "kg", average_price: 55.0 },
        { name: "Cebola", unit: "kg", average_price: 1.5 },
        { name: "Manjericão", unit: "kg", average_price: 1.5 },
      ],
    },
    RR: {
      ingredients: [
        { name: "Massa de Pizza", unit: "kg", average_price: 7.7 },
        { name: "Molho de Tomate", unit: "kg", average_price: 7.1 },
        { name: "Queijo Mussarela", unit: "kg", average_price: 54.0 },
        { name: "Calabresa", unit: "kg", average_price: 44.0 },
        { name: "Frango Desfiado", unit: "kg", average_price: 49.0 },
        { name: "Milho", unit: "kg", average_price: 13.7 },
        { name: "Azeitonas", unit: "kg", average_price: 31.5 },
        { name: "Ovos", unit: "dz", average_price: 5.0 },
        { name: "Presunto", unit: "kg", average_price: 56.0 },
        { name: "Cebola", unit: "kg", average_price: 1.6 },
        { name: "Manjericão", unit: "kg", average_price: 1.6 },
      ],
    },
  },
  recipes: [
    {
      name: "Pizza de Calabresa",
      ingredients: [
        { name: "Massa de Pizza", quantity: 1.0 },
        { name: "Molho de Tomate", quantity: 0.2 },
        { name: "Queijo Mussarela", quantity: 0.3 },
        { name: "Calabresa", quantity: 0.25 },
        { name: "Azeitonas", quantity: 0.05 },
      ],
    },
    {
      name: "Pizza de Frango",
      ingredients: [
        { name: "Massa de Pizza", quantity: 1.0 },
        { name: "Molho de Tomate", quantity: 0.2 },
        { name: "Queijo Mussarela", quantity: 0.3 },
        { name: "Frango Desfiado", quantity: 0.25 },
        { name: "Milho", quantity: 0.1 },
      ],
    },
    {
      name: "Pizza de Queijo",
      ingredients: [
        { name: "Massa de Pizza", quantity: 1.0 },
        { name: "Molho de Tomate", quantity: 0.2 },
        { name: "Queijo Mussarela", quantity: 0.3 },
        { name: "Azeitonas", quantity: 0.1 },
      ],
    },
    {
      name: "Pizza Portuguesa",
      ingredients: [
        { name: "Massa de Pizza", quantity: 1.0 },
        { name: "Molho de Tomate", quantity: 0.2 },
        { name: "Queijo Mussarela", quantity: 0.3 },
        { name: "Presunto", quantity: 0.25 },
        { name: "Ovos", quantity: 0.1 },
        { name: "Cebola", quantity: 0.1 },
        { name: "Azeitonas", quantity: 0.05 },
      ],
    },
    {
      name: "Pizza Marguerita",
      ingredients: [
        { name: "Massa de Pizza", quantity: 1.0 },
        { name: "Molho de Tomate", quantity: 0.2 },
        { name: "Queijo Mussarela", quantity: 0.3 },
        { name: "Manjericão", quantity: 0.05 },
      ],
    },
  ],
};

export const recipesNames = [
  "Pizza de Calabresa",
  "Pizza de Frango",
  "Pizza de Queijo",
  "Pizza Portuguesa",
  "Pizza Marguerita",
];
